import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/*header*/}
        <header style={{ padding : 12 }}> 
          <nav>
            <Link href="/">home</Link> {" | "}
            <Link href="/about">about</Link> {" | "}
            <Link href="/portfolio">portfolio</Link> {" | "}
          </nav>
        </header>
        {/*page content*/}
        <main stype={{ padding :12 }}>{children}</main> 
      </body>
    </html>
  );
}
